#ifndef DOOM_DEPTH_C_LEVEL_UP_SCREEN_TYPES_H
#define DOOM_DEPTH_C_LEVEL_UP_SCREEN_TYPES_H

typedef enum {
    STAT_HP = 0,
    STAT_MANA,
    STAT_DEFENCE,
    STAT_ATTACK,
    STAT_ACTION_POINTS,
    STAT_COUNT
} stat_t;

#endif //DOOM_DEPTH_C_LEVEL_UP_SCREEN_TYPES_H
